### ISSUE TITLE
mypipe creates hundreds of MySQL connections

### ISSUE THREAD

**Issue by ldcasillas-progreso** [mardambey/mypipe#10]
This is possibly related to issues #8 and #9.  When I start up mypipe, it starts creating connection after connection to MySQL.  The connections run queries like this one, and then sleep:

```
select COLUMN_NAME from KEY_COLUMN_USAGE where TABLE_SCHEMA='<CENSORED>' and TABLE_NAME='<CENSORED>' and CONSTRAINT_NAME='PRIMARY' order by ORDINAL_POSITION
```

Soon the MySQL server's connection limit is reached, and we get these:

```
407637 [db-async-netty-thread-7] ERROR [mysql-connection-807] - Received an error message -> ErrorMessage(1040,Too ma,ny connections)
407637 [db-async-netty-thread-8] ERROR [mysql-connection-808] - Received an error message -> ErrorMessage(1040,Too ma,ny connections)
[ERROR] [02/26/2015 11:33:23.388] [mypipe-akka.actor.default-dispatcher-2] [akka://mypipe/user/DBMetadataActor-dev-db03.dev.pfoperations.com:3306] Error 1040 - Too ma - ny connections
com.github.mauricio.async.db.mysql.exceptions.MySQLException: Error 1040 - Too ma - ny connections
    at com.github.mauricio.async.db.mysql.MySQLConnection.onError(MySQLConnection.scala:135)
    at com.github.mauricio.async.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.scala:103)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by mardambey** [comment]
@ldcasillas-progreso if you connect to the database using the same credentials that mypipe uses, can you run that query successfully?

**Comment by ldcasillas-progreso** [comment]
I think I've pinpointed the problem.  The user doesn't have a default database.  So when I connect with the `mysql` client program and run the query I get this:

```
ERROR 1046 (3D000): No database selected
```

I'd say that it definitely can't hurt to explicitly specify the `information_schema` database in the query:

```
select COLUMN_NAME 
from INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
where TABLE_SCHEMA='<CENSORED>' 
and TABLE_NAME='<CENSORED>' 
and CONSTRAINT_NAME='PRIMARY' 
order by ORDINAL_POSITION
```

**Comment by ldcasillas-progreso** [comment]
...but looking at `MySQLMetaDataManager.scala`, the connection is created with `information_schema` as its database, so I'd be suprised if this was relevant at all.

So to answer your question, yes, I can execute the query successfully, provided that the user has the correct database set.

**Comment by ldcasillas-progreso** [comment]
I just tried adding the `INFORMATION_SCHEMA` qualifier to the table names in `MySQLMetaDataManager.scala`, and it doesn't make the problem go away.
