### ISSUE TITLE
Specific schema format

### ISSUE THREAD

**Issue by eugenemiretsky** [mardambey/mypipe#25]
Hi! 

Couldn't find documentation for the format of  Specific Avro schemas.
 From what I can tell from the code,
1)  The schema name is  s"${db}_${table}_${mtype}" (type being update/insert/delete).
2)  For inserts the  schema  is expected to just have all the columns
3)  For updates the schema is expected to have old_<column_name>  and  new_<column_name> 

Is there something I'm missing?

Also, for most updates only 1 column gets updated, it seems somewhat inefficient to send all the new & old values for each column.

**Comment by mardambey** [comment]
@eugenemiretsky take a look at bb7acf47f9e80b8792b4ed517fa16d82763bd3c9. This is by no means complete (or tested yet). Perhaps this will get you on the right path and you can fill in the blanks.

Regarding sending the entire row versus only the changed columns, this could possibly be added as an option. Currently, by maintaining all the column information, we can use Kafka's topic compression in order to have a topic that will allow you to bootstrap an empty MySQL DB or other stores from the Kafka topic.

**Comment by bbnsumanth** [comment]
Hi,i'm trying to run mypipe,but i'm getting the following error.can u please hellp me to fix that.
Thanks in advance :)
java.util.NoSuchElementException: key not found: 127.0.0.1
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at mypipe.runner.PipeRunnerUtil$$anonfun$createPipes$1$$anonfun$3.apply(PipeRunner.scala:76)
	at mypipe.runner.PipeRunnerUtil$$anonfun$createPipes$1$$anonfun$3.apply(PipeRunner.scala:75)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mypipe.runner.PipeRunnerUtil$$anonfun$createPipes$1.apply(PipeRunner.scala:75)
	at mypipe.runner.PipeRunnerUtil$$anonfun$createPipes$1.apply(PipeRunner.scala:63)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at mypipe.runner.PipeRunnerUtil$.createPipes(PipeRunner.scala:63)
	at mypipe.runner.PipeRunner$.pipes$lzycompute(PipeRunner.scala:22)
	at mypipe.runner.PipeRunner$.pipes(PipeRunner.scala:22)
	at mypipe.runner.PipeRunner$.delayedEndpoint$mypipe$runner$PipeRunner$1(PipeRunner.scala:24)
	at mypipe.runner.PipeRunner$delayedInit$body.apply(PipeRunner.scala:13)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at mypipe.runner.PipeRunner$.main(PipeRunner.scala:13)
	at mypipe.runner.PipeRunner.main(PipeRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
[trace] Stack trace suppressed: run last runner/compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)

**Comment by bbnsumanth** [comment]
my application.cnfg file


mypipe {

  # consumers represent sources for mysql binary logs
  consumers {

    database1 {
      # database "host:port:user:pass" array
      #source = "database1:3306:root:foobar"
      source  = "127.0.0.1:3307:root:root"
      
    }

  }

  # data producers export data out (stdout, other stores, external services, etc.)
  producers {

    stdout {
       class = "mypipe.producer.stdout.StdoutProducer"
    }
  
    #kafka-generic {
     #   class = "mypipe.producer.KafkaMutationGenericAvroProducer"
    #}

  }

  # pipes join consumers and producers
  pipes {

    stdout {
      consumers = ["127.0.0.1"]
      producer {
        stdout {}
      }
    }

    #kafka-generic {
     #   enabled = true
      #  consumers = ["127.0.0.1"]
       # producer {
        #  kafka-generic {
         #    metadata-brokers = "localhost:9092"
          #}
        #}
    #}
  }

}

include "application.overrides"
