### ISSUE TITLE
 No configuration setting found for key 'mypipe.producers'

### ISSUE THREAD

**Issue by jb-san** [mardambey/mypipe#49]
Hi, after following the readme to get started i encounter:

```
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'mypipe.producers'
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'mypipe.producers'
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
        at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:218)
        at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:33)
        at mypipe.api.Conf$.loadClassesForKey(Conf.scala:64)
        at mypipe.runner.PipeRunnerUtil$.loadProducerClasses(PipeRunner.scala:46)
        at mypipe.runner.PipeRunner$.producers$lzycompute(PipeRunner.scala:23)
        at mypipe.runner.PipeRunner$.producers(PipeRunner.scala:23)
        at mypipe.runner.PipeRunner$.pipes$lzycompute(PipeRunner.scala:25)
        at mypipe.runner.PipeRunner$.pipes(PipeRunner.scala:25)
        at mypipe.runner.PipeRunner$.delayedEndpoint$mypipe$runner$PipeRunner$1(PipeRunner.scala:27)
        at mypipe.runner.PipeRunner$delayedInit$body.apply(PipeRunner.scala:16)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at mypipe.runner.PipeRunner$.main(PipeRunner.scala:16)
        at mypipe.runner.PipeRunner.main(PipeRunner.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
[trace] Stack trace suppressed: run last runner/compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last runner/compile:runMain for the full output.
[error] (runner/compile:runMain) Nonzero exit code: 1
[error] Total time: 1 s, completed Feb 2, 2016 6:43:37 PM
```

mypipe-runner/application.conf: 

```
# consumers represent sources for mysql binary logs
consumers {

database1  {
    # database "host:port:user:pass"
    source = "localhost:3306:root:root"
  }
}
producers {
  stdout {
     class = "mypipe.producer.stdout.StdoutProducer"
  }
}
pipes {

  # prints queries to standard out
  stdout {
    consumers = ["database1"]
    producer {
      stdout {}
    }
  }
}
```

any help is much appreciated

**Comment by jb-san** [comment]
sorry my bad for not checking the resources folder first
