### ISSUE TITLE
[ERROR] java.util.concurrent.TimeoutException: Futures timed out after [1 second]

### ISSUE THREAD

**Issue by ldcasillas-progreso** [mardambey/mypipe#9]
Companion to issue #8.  I see many instances of this error message:

```
[ERROR] [02/26/2015 10:58:10.358] [mypipe-akka.actor.default-dispatcher-4] [akka://mypipe/user/DBMetadataActor-dev-db03.dev.pfoperations.com:3306] Futures timed out after [1 second]
java.util.concurrent.TimeoutException: Futures timed out after [1 second]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
    at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
    at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
    at scala.concurrent.Await$.result(package.scala:107)
    at mypipe.mysql.MySQLMetadataManager$$anonfun$2.apply(MySQLMetadataManager.scala:56)
    at mypipe.mysql.MySQLMetadataManager$$anonfun$2.apply(MySQLMetadataManager.scala:44)
    at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
    at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
    at mypipe.mysql.MySQLMetadataManager.getTableColumns(MySQLMetadataManager.scala:44)
    at mypipe.mysql.MySQLMetadataManager$$anonfun$receive$1.applyOrElse(MySQLMetadataManager.scala:37)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at mypipe.mysql.MySQLMetadataManager.aroundReceive(MySQLMetadataManager.scala:22)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Sometimes the message says 1 second, sometimes 2.

**Comment by ldcasillas-progreso** [comment]
Increasing the timeouts in the `Await.result` calls in `MySQLMetadataManager.scala` appears to make these go away.  It also alleviates Issue #10.
